### ISSUE TITLE
Exception in thread, Traceback and unable to assign requested address

### ISSUE THREAD

**Issue by monikeraudio** [jms5194/Digico-Reaper-Link#4]
Have installed dependencies and running todays updated script - I admit to not being very well versed in programming but can trace OSC packets and they are leaving the console and not being received on the loopback address. 

<img width="1453" alt="Screen Shot 2022-06-08 at 3 56 22 pm" src="https://user-images.githubusercontent.com/98502742/172705687-6db8566d-f140-42fb-b38e-980de03f7c1c.png">

**Comment by jms5194** [comment]
Hi!

What OS are you running on? If you are running on MacOS, please use the compiled application that you can download from the releases page on the right hand side of the page. If you want the new features I've added today (repeater for ipad support), you may need to wait a couple days for me to push a release. 

Otherwise, that error stack doesn't really look like an error per say, just looks like it couldn't connect to the remote device. Are your settings correct in the preferences window in terms of remote IPs and ports?

**Comment by monikeraudio** [comment]
Hi, 

Great to be in touch - I'm testing on both PC and OSX. With my lack of knowledge in Python I'm tracing packets in Wireshark. I can trace the OSC into the host from the console, but can't see anything coming out on the loopback address.

The screenshot was from when I was offline, and that last error line goes away when connected properly. Would any of the other notes regarding the socketserver be a cause of messages not passing through to the loopback, or is this normal?

**Comment by jms5194** [comment]
When all of the IP configuration is correct, you shouldn't see any of those log messages. It should just say "Reaper OSC Server started", "Digico OSC Server Started" "Repeater OSC Server Started". 

Can you send me pictures of your "External Controls" window on the console, your preferences window in Digico-Reaper Link, and your Control/OSC/Web preference page in Reaper?

**Comment by monikeraudio** [comment]
OK - i tried a different approach and edited the default IP address in IDLE to the IP addresses I needed instead of using the preferences. I found that the same errors would occur when updating the preferences, and then when re-loading the program the addresses had returned to default.

Now I get a clean load as you outline above, unfortunately still not receiving communication in REAPER. Settings attached below...

![IMG_2335](https://user-images.githubusercontent.com/98502742/172733374-c8e2723a-b172-4672-a2ab-71bd0b2d8994.jpg)
![IMG_2333](https://user-images.githubusercontent.com/98502742/172733380-f4b1a19b-8a3d-46af-ae85-9076426b10f5.jpg)

**Comment by jms5194** [comment]
Ok, thanks for this. I'm seeing a couple issues here now. I have never tested the configuration storage portion of this in Windows, I'm working in MacOS, so let me take a look at this this evening on a windows machine and see what happens there. It seems that it is not storing the configuration persistently on Windows. Everything else looks good to me. So this is probably a problem in the code as it relates to Windows. Let me try and take a look at this tonight and I'll get back to you.

**Comment by jms5194** [comment]
Can you please try and download the code again? I think you may have caught a commit that was right inbetween versions. I think you have the most current main.py but an older UI.py.

**Comment by jms5194** [comment]
That doesn't solve your preferences issue, but might fix your problems with connectivity.

**Comment by jms5194** [comment]
I think this should be solved now. Can you grab new versions of the script and test on your side? I'll build a windows install version if it works for you now.

**Comment by ccampbelltt26** [comment]
Interested if the Windows installer has been made?

**Comment by jms5194** [comment]
Hi- there is now an actual Windows version in releases- https://github.com/jms5194/Digico-Reaper-Link/releases/latest. 

I'm testing it right now on a windows machine and it seems good so far. The only gotcha was that I had to manually let it though Windows Defender to allow it to communicate with the Digico. Let me know how things are looking for you now.

**Comment by jms5194** [comment]
I'm going to close this issue now since I've been testing the Windows version for myself the past couple weeks and it seems to working well for me. But let me know if you continue to experience any issues with the newest windows version!
