### ISSUE TITLE
Random App Crashes

### ISSUE THREAD

**Issue by adaminchicago** [jms5194/Digico-Reaper-Link#5]
I've been using the compiled Mac OS version for quite some time now with pretty good success.  I have an issue that has followed me across multiple machines and multiple operating systems where the app just randomly crashes.  Attaching the Mac OS Problem Report here in case you're able to find anything of use in it.

[DRL Crash Report copy.odt](https://github.com/jms5194/Digico-Reaper-Link/files/11444994/DRL.Crash.Report.copy.odt)

**Comment by jms5194** [comment]
Hey, Thanks for the crash report. I'll take a look at this and see if I can come up with anything. I've heard of a report where the app crashes when it is being closed, and then loses its preferences. Is this what you're experiencing, or is this just a crash that occurs when you normally using it?

**Comment by adaminchicago** [comment]
It happens while it’s running, not while it’s being closed and when it does, it does not lose its preferences.  Today it happened while I wasn’t even in front of the computer.  Both the computer and the console were idle.

**Comment by jms5194** [comment]
Ok, thanks for that information. I'll take a look at the crash report.

**Comment by jms5194** [comment]
Hey Adam- 
I've release a new major release version- let me know if that solves your issues: https://github.com/jms5194/Digico-Reaper-Link/releases/latest

**Comment by adaminchicago** [comment]
Thanks Justin. I continue to use this with almost all of my Digico setups and regularly have peers come to me asking to get them set up as well.  Excited to try a new major release.

**Comment by jms5194** [comment]
Cool- glad to hear it's useful for you! I'm working on the updated Readme docs now, but basic new things are: much easier configuration- it now sets up Reaper for you, and only requires the console IP and ports for the console, it has a heartbeat function in the UI for the console, support of macro keys for transport and marker drop, the MacOS app now has native versions for both Intel and Arm processors (and is now notarized and code-signed), and there is a Windows version available.

**Comment by jms5194** [comment]
Hey Adam- I'm going to close this issue with the new version being a pretty complete re-write. But let me know if you still end up seeing any crashes with the new version!

**Comment by adaminchicago** [comment]
Thanks Justin - I will keep you posted.  I use this on pretty much every Digico setup I mix on (and most of what I mix on is Digico) except for the 7 (a story for another day) and all of my colleagues are always coming to me asking to set it up for them.  This new version makes it so much better!
