### ISSUE TITLE
Unable to get to work since recent updates.

### ISSUE THREAD

**Issue by tricamtech** [jms5194/Digico-Reaper-Link#8]
I can't seem to get this to work any longer with the most recent release. I am on the most current Q225 firmware and current reaper. 
When I "listen for OSC" in reaper I never get any commands. 
Let me know what else you would like to know to troubleshoot. 

I used this last year at this time and it was great. Same gig this year and I can't make it work with all the same gear and network settings etc.

**Comment by monikeraudio** [comment]
First of all I would try rolling back External Waves to Legacy if you are currently using ProlinkSent from my iPhoneOn 21 Sep 2024, at 12:23 PM, tricamtech ***@***.***> wrote:﻿
I can't seem to get this to work any longer with the most recent release. I am on the most current Q225 firmware and current reaper.
When I "listen for OSC" in reaper I never get any commands.
Let me know what else you would like to know to troubleshoot.
I used this last year at this time and it was great. Same gig this year and I can't make it work with all the same gear and network settings etc.

**Comment by jms5194** [comment]
Interesting. Sorry it's not working for you. Can you post a picture with your settings in the app, reaper and on the console? I'm currently using it on a number of desks including a Quantum 7 with Legacy Waves and a SD9 with Waves ProLink. I really don't think that Waves version should have anything to do with it- it shouldn't know really anything about waves. The version of code that is here is much newer than the release, but much less tested. Are you using the released version or are you building off of the actual python?

**Comment by jms5194** [comment]
Hi all- 
I've just released a major new revision with a bunch of updates- I'm going to update the readme soon with the info but hopefully in any case this will solve your issues. Check out [https://github.com/jms5194/Digico-Reaper-Link/releases/latest/](url).

**Comment by jms5194** [comment]
I'm going to close this issue since I hope the newest versions should solve all your issues- but let me know if otherwise!
